### ISSUE TITLE
Fix MongoDB version

### ISSUE THREAD

**Issue by alfabravo2013** [Hyperskill-Community/flashcards#10]
Currently, the project uses the 'mongo:latest' image. This has the following drawbacks:
- Docker always checks if the local image is up to date and pulls a newer version if it's found.
- As time passes, the latest version changes which eventually may lead to compatibility issues.
- We can take advantage of using a lower size image both for development and production.

@wisskirchenj Considering the above, I propose to choose and fix the MongoDB image version.

**Comment by wisskirchenj** [comment]
completed - set 7.0.4

**Comment by wisskirchenj** [comment]
completed - set 7.0.4
