### ISSUE TITLE
Create flashcard models

### ISSUE THREAD

**Issue by alfabravo2013** [Hyperskill-Community/flashcards#13]
Extracted from Issue #5:
Add some basic Card.java @Documentclass, that is extensible enough to serve as the base class for all our flash cards documents - i.e. the instances that make up the collection
-> consider abstract or sealed class - but not exaggerated complexity. Derived classes could be SimpleQAndACard, MultipleChoiceCard, and may well be records)

**Comment by wisskirchenj** [comment]
Typical sequence of creating new card - happy case:

1) Frontend provides you via POST with data containing 

- user => used for author in card document (and for access list in category document iff this is the first document of that category)
- category => defines the collection name, the new card is inserted and to be created (if not exists)
- title => all belwo are Card data fields
- question
- answer
- tags
- ...

2) Backend service gets the collection with the provided category (or create if not exists)
2b) if it does not exist, backend inserts a new document **in collection category** , that has the category as name and give it an initial access array with one element "username": "rwd" (for read, write and delete)
3) backend inserts the card document with posted data (from title below) into the collection for this category
4) returns created response (204) to frontend

Example (no collection yet for "math"):
1) POST 
```json
{
"user": "william",
"category": "math",
"title": "Title",
...
"tags": [ "algebra", "exam"]
}
```
2) create collection "math" and insert:
```json
{
"title": "Title",
...
"tags": [ "algebra", "exam"],
"author": "william".  // or creator?
"createdAt": <timestamp>
}
```
2b) new document inserted into collection `category`:
```json
{
"name": "math"
// there may be a description later or more fields, that are part of some "new collection" workflow with UI
"access": [{
    "william": "rwd"
  }]
}
```
