### ISSUE TITLE
Add backend tests

### ISSUE THREAD

**Issue by wisskirchenj** [Hyperskill-Community/flashcards#18]
provide some backend tests for new code

**Comment by alfabravo2013** [comment]
Added unit and integration tests for database initializer component. As expected, now we have mongo container reusability problem: the occupied port is not released between tests. Check [this branch](https://github.com/Hyperskill-Community/flashcards/tree/issue18/add-db-initializer-tests).
I still have no idea why the container is not working properly without port bindings.
@wisskirchenj if you try to investigate it too, I'd appreciate.
