### ISSUE TITLE
Docker compose setup

### ISSUE THREAD

**Issue by alfabravo2013** [Hyperskill-Community/flashcards#2]
Spring Boot docker compose settings should be fine-tuned and better documented.
Matters to concider and make a decision:
- **Container lifecycle**. Should it start and stop upon the application startup / shutdown or should start one and run until stopped?
- **MongoDB volume**. `README.md` should provide an instruction how to remove the volume from the local machine if needed.
- **Docker compose file location**. Currently, the application's working directory is `server/` while the `compose.yaml` is in the parent directory. This causes inconvenience when running gradle tasks from the command line. The file location should be set in the `application.properties`.

**Comment by wisskirchenj** [comment]
- The docker compose path issue will be solved with the gradle Bootrun addition IMO. So I will not add a path property, but checkin a Run Configuration to start the App, that Devs can also tranfer into Service Tool window & add Readme for it

- container lifecycle: I see no reason to have the MongoDb container run after the app shuts down. Starting up the container takes maybe 1 second (once it is among the Images) and we persist into a volume. So an unnecessary running container would annoy me mostly. Only pro for having it run I see, is that the Database Tool Window would work in IntelliJ when Developing - but in fact that is the usecase for the TestApplication from(...).with(...) tht spring.io sets up.
=> I would leave the Lifecycle as is

- mongoDb volume: Agreed - though you can easily remove it with Docker Desktop (that's what I do). But there is no harm in providing a shell script - or option in compose.yml.
@alfabravo2013: Do you have a preferred solution here?

**Comment by alfabravo2013** [comment]
Thanks for explanations!
I agree with container lifecycle and the test application config, it makes sense. I'd be nice to mention it in the README.
An instruction in README how to remove container data altogether would be enough.

@wisskirchenj this entire issue actually can be solved by adding a few lines in README.md.

**Comment by alfabravo2013** [comment]
All necessary changes applied.
