### ISSUE TITLE
MongoDB testcontainers - dynamic port mapping

### ISSUE THREAD

**Issue by alfabravo2013** [Hyperskill-Community/flashcards#29]
Current config does not provide proper connection and integration tests fail.
- With default container config, the container bean cannot establish connection and a test fails with connection timeout.
- With the current config, the container provides fixed port mapping intead of dynamic and the mapped port 27017 is not released upon completion of the first test, which makes the next test fail.
- Test application, however, runs smoothly both with the default and fixed port bindings.

Investigate how to fix this connectivity problem.

**Comment by wisskirchenj** [comment]
The bug is fixed with the reuse - but dynamic portmapping can still be improved

**Comment by wisskirchenj** [comment]
fixed this BUG (which it really was) by removing a MongoTemplate bean with wrong defaults, that compromised the Testcontainer ServiceConnection.

**Comment by wisskirchenj** [comment]
.
