### ISSUE TITLE
adapt PageDetails to fetch real data from backend app via axios

### ISSUE THREAD

**Issue by wisskirchenj** [Hyperskill-Community/flashcards#35]
- Structure the Page created in #16 into components.
- Make its card data dynamic  
- communicate parent child via props and emits
- retrieve displayed data via axios from backend app (Oauth token)
- improve optical appearance

**Comment by Averageasd** [comment]
the id input field is not there anymore. I am not sure if I need to make one. I asked this question because I need to test if my code for page detail works.
