### ISSUE TITLE
Add CRUD endpoints for flashcards

### ISSUE THREAD

**Issue by alfabravo2013** [Hyperskill-Community/flashcards#44]
Add support for creating, finding, updating and deleting flashcards:
- `POST /api/cards` to create a new flashcard by type
- `PUT /api/cards/:cardId` to update an existing card
- `DELETE /api/cards/:cardId` to delete an existing card

**Comment by Averageasd** [comment]
I think we should have GET /api/cards/:cardId as well. Based on my understanding of the codebase, this feature is also missing.
