### ISSUE TITLE
Id input field for card?

### ISSUE THREAD

**Issue by Averageasd** [Hyperskill-Community/flashcards#48]
Ok I am thinking that we will need an input field that accepts card id from user.

**Comment by alfabravo2013** [comment]
Why?

**Comment by Averageasd** [comment]
so initially there was an input field for card id but it's gone. However, ig we dont need it anymore.

**Comment by wisskirchenj** [comment]
@Averageasd: I suggest to close this now - as we can set id in browser url now. And later UX will be different anyway.
OK for you?

**Comment by Averageasd** [comment]
yeah. Ok, so let's close it.
