### ISSUE TITLE
Intitial cards model and data population of mongoDB.

### ISSUE THREAD

**Issue by wisskirchenj** [Hyperskill-Community/flashcards#5]
**EDIT:** Add some basic Card.java `@Document`class, that is extensible enough to serve as the base class for all our flash cards documents - i.e. the instances that make up the collection 
-> consider abstract or sealed class - but not exaggerated complexity. Derived classes could be SimpleQAndACard, MultipleChoiceCard, and may well be records)
*--- end of edit to data model --- added, since it is probably needed for the population task below ---*

Add some initial data to populate the mongoDB:

- a sample user (to the user collection)
- some initial card data - as an example collection `db.example`.

The data are well-suited for us now in early development phase, as they can be used for implementing display / modification views. But they can also stay in permanently and serve to new users to flashcards as public card sample collection to get familiar.

Incrementally, the example collection should consist of different card types as simple Q&A, multiple choice, etc.. to illustrate the options a user has.

Several alternatives - increasingly more effort - on how to implement the task (all alternative should only insert, if the example collection does not yet exist)

1. **Insert manually per script**. 
Use init script to insert data  - like 5 to 10 Json records for a start (comparable to `spring.sql.init.data-locations=classpath:initData.sql`)
2. **Insert manually via CommandLineRunner**. 
same as 1 only Commandlinerunner
3. **use quiz data from the net**.  
find and download some suitable (maybe a little larger) quiz data set and transform it into our cards example collection by use of a CommandLineRunner.
4. **scrape website and generate cards**
e.g. use the problems of some Hyperskill topic group (e.g. Spring)

**Comment by alfabravo2013** [comment]
@wisskirchenj I'd like you to clarify your vision:
- you want to use `MongoTemplate` in the project rather than `MongoRepository`, right?
- We can add the example collection as a database initialization script in `compose.yaml`. Alternatively, as you mentioned, we can deal with the initialization in a `CommandLineRunner` component. Pros and cons of these solutions are obvious, the first one requires more actions if the example data changes, while the latter requires json parsing and employing additional safeguards against data duplication. Anyway, the `CommandLineRunner` option looks more flexible at the current stage. What dou you think?
- I advise against borrowing data from HS because their materials are copyrighted.

**Comment by wisskirchenj** [comment]
@alfabravo2013:
I am also quite new to (Spring) Mongo DB - but I skimread the Spring support. And it seems to me that the MongoRepository is not well-suited as it assign some Document class/record to a repository and also derives the collection name in the DB from that.
BUT - at least in my vision - each category of flash cards (say English vocabulary, Java, Math) gets stored in its own collection, but has no different structure in its model classes.

So my vision of the cards data are several collections that contain structurally equal or similar model classes => namely (as I indicated above) the different kinds of supported CardTypes - e.g. permitted classes if we use sealed for Card.java
This would be like SimpleQAndACard or MultipleChoiceCard or GapFillingCard, ...

=> So, YES I guess we can implement that well using the MongoTemplate as our DB-Access Bean.

**Comment by wisskirchenj** [comment]
@alfabravo2013:
Concerning data initialization:
Well good to know, we are not allowed to scrape HS-data..
Then I agree, we use a CommandLineRunner to insert data in the database (iff the example collection does not exist)
Some like 5 to 10 cards would be enough for a start - or with few googling we find some nice open source set of cards, that we insert...
Also we should insert 1 test user, so a newbie installing the app can already login without registering a user...

**Comment by wisskirchenj** [comment]
More thoughts - copied in here from chat for not losing track...:
I guess besides the collections user and  card-collections topic1, topic2, etc., we will need one meta-data collection category or sth similar, whose documents describe each one topic-collection.
I.e. it would be modelled with

- name (e.g. "topic1")
- description
- access (an array saying which users may access this cards collection, besides users (name or id), this array should have a value of "public", which when there, allows all users to access this collection)

In Json we could model an entry in this access array nested as { "user1": "rwd" } 
or { "user2": "r"} to set more fine-grained permissions

**Comment by wisskirchenj** [comment]
@alfabravo2013: Not sure, what is open here - or what you are stills eeing under this issue (if any)
So please check

**Comment by alfabravo2013** [comment]
> @alfabravo2013: So please check

DB initialization issue is derived from this so I will close this one as soon as I close Issue #14 with the PR #20
