### ISSUE TITLE
Fix issues and bugs identified by Sonarqube in flashcards

### ISSUE THREAD

**Issue by alfabravo2013** [Hyperskill-Community/flashcards#53]
The list of issues can be found at `http://localhost:9000/project/issues?id=flashcards-server`.

**Comment by wisskirchenj** [comment]
backend now fully test covered (>95%) and no sonar issues, smells left
All quality gates pass..

**Comment by wisskirchenj** [comment]
backend now fully test covered (>95%) and no sonar issues, smells left
All quality gates pass..
